db:
  host: "127.0.0.1"       
  port: 3306              
  user: "root"            
  password: "123456xx"    
  dbname: "lockinraft"
raft:
  bootStrap: true
  httpAddr: "127.0.0.1:7001"
  raftAddr: "127.0.0.1:7000"
  raftId: "1"
  raftCluster: "1/127.0.0.1:7000"
  raftDir: "node/raft"
http:
  port: 7070
  readTimeout: 10
  writeTimeout: 10
  maxHeaderBytes: 1024